### ISSUE TITLE
要把自己寫的部分獨立 Commit

### ISSUE THREAD

**Issue by demofan** [YuChia-Wei/SkillTree-MVC-HW#1]
你將預設範本與你修改的使用同一份上傳，我無法看出哪些你有調整，所以請重新 commit 你有修改的版本。

PS.隨意看了一下，你並沒有符合規定中的相關事項

1. 日期格式

**Comment by YuChia-Wei** [comment]
> 你將預設範本與你修改的使用同一份上傳，我無法看出哪些你有調整，所以請重新 commit 你有修改的版本。
> 
> PS.隨意看了一下，你並沒有符合規定中的相關事項
> 
> 1. 日期格式

日期格式目前已修改
Commit 1 & 2 即是原始範本
Commit 3 (Tag 2019-07-06-HW) 為我完成的內容，主要完成了以下項目

- 增加 AccountingController
- 增加 PersonalAccountingViewModel
- 調整進入點 (Route) ，由 Home 移動到 Accounting，所以網站主頁為 View/Accounting/Index

Commit 4 (Tag 2019-07-06-HW.1) 修改了日期格式，並增加了金額類別的顯示 (使用英文)
